### ISSUE TITLE
ImportError: No module named 'get_smarties' with python 3.5.2

### ISSUE THREAD

**Issue by stellasia** [joeddav/get_smarties#1]
Hi,

I have pip installed this package in my virtualenv as suggested in README: `pip install git+https://github.com/joeddav/get_smarties.git` but when trying to import I get this ImportError. 

Any idea ? 

I am using python 3.5.2

**Comment by TengGao** [comment]
I also have the same issue, and I use Anaconda. Is it an compatibility issue?
Is there a way to manually install the package instead of using pip?

**Comment by joeddav** [comment]
That's odd. Try cloning the repo and installing locally with `pip install path/to/repo`

**Comment by paulochf** [comment]
Got the same issue. Cloning and installing locally didn't work.

**Comment by joeddav** [comment]
This seems like an issue with how anaconda uses pip, and I'm afraid I'm not an anaconda expert. I'd check out https://github.com/ContinuumIO/anaconda-issues/issues/1429. Looks like some helpful tips there. Please post here if you get a fix.

**Comment by paulochf** [comment]
I'm sorry, I forgot to mention: I don't use Anaconda, Python version is 3.6.3.

**Comment by joeddav** [comment]
Sorry guys, my instructions were faulty. I replicated the issue and the following worked for me:

```
pip install -e git+https://github.com/joeddav/get_smarties.git#egg=get_smarties
```

Let me know if that doesn't work.

**Comment by paulochf** [comment]
Worked for me, thanks!

**Comment by stellasia** [comment]
Sorry for the lack of feedbacks but thanks for fixing it! 

I just had to add quotes on zsh:

    pip install -e "git+https://github.com/joeddav/get_smarties.git#egg=get_smarties"
