### ISSUE TITLE
'Smarties' object has no attribute 'get_params'

### ISSUE THREAD

**Issue by DataDave-datajoi** [joeddav/get_smarties#3]
If I am grid searching over a pipeline that uses Smarties, how might I set or skip over the 'get_params'?

**Comment by joeddav** [comment]
I'm not sure exactly how sklearn's grid search works, but I'd try just subclassing Smarties and implementing an empty `get_params` like such:

```python3
class SKSmarties(Smarties):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
    def get_params(self, deep=True):
        return {}
```

Or just adding it directly to the source code. See if that works. If it does, let me know and we can probably just add it to the base.

**Comment by joeddav** [comment]
Closing this for now.
