### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by InCogNiTo124** [joeddav/get_smarties#4]
I'm using pandas 0.23.1 and everytime I import get_smarties I get an error:

 FutureWarning: 'pandas.core' is private. Use 'pandas.Categorical'
  from pandas.core.categorical import _factorize_from_iterable
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-1fe3fcf1ed66> in <module>()
----> 1 import get_smarties

...\get_smarties.py in <module>()
      5 from pandas.core.frame import DataFrame
      6 from pandas.core.indexing import is_list_like
----> 7 from pandas.core.categorical import _factorize_from_iterable
      8
      9 class Smarties:

ImportError: cannot import name '_factorize_from_iterable'

**Comment by NickBaguley** [comment]
Just in case others find this. Adding .arrays. is the fix:

from pandas.core.arrays.categorical import _factorize_from_iterable
